spring:
  datasource:
    url: jdbc:h2:mem:testdb

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

sql:
  init:
    mode: always
    data-locations: data.sql
    schema-locations: schema.sql

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true