spring:
  data:
    mongodb:
      host: localhost
      port: 0
      database: test

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.pk.spring.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
