###
GET http://localhost:8080/actuator

###
GET http://localhost:8080/books

###
GET http://localhost:8080/books/2

###
DELETE http://localhost:8080/books/122213

###
POST http://localhost:8080/books
Content-Type: application/json

{
  "id": null,
  "name": "newwwwewww1111",
  "authorId":2123,
  "genreId": 11
}

###
PUT http://localhost:8080/books
Content-Type: application/json

{
  "id": 2554,
  "name": "mmmm",
  "authorId":2,
  "genreId": 1
}

###
GET http://localhost:8080/book/2/comments

###
POST http://localhost:8080/comments
Content-Type: application/json

{
  "id": null,
  "text": "newComment",
  "bookId": 2
}

###
DELETE http://localhost:8080/comments/1

####
#GET http://localhost:8080/books/13423
#
#> {%
#      client.test('should return 200 OK', function () {
#          client.assert(response.status === 200, 'Wrong status code');
#      })
#
# %}

